### ISSUE TITLE
Navbar and basic layout

### ISSUE THREAD

**Issue by YoYuUm** [fastmonkeys/huvaja#12]

**Comment by lraivio** [comment]
@YoYuUm: At this point you can keep the layout and navbar very simple.
Layout:
- Probably adding [Grid](https://react-bootstrap.github.io/components.html#grid-props-grid) to `AppContainer` is enough.

Navbar:
- Use Navbar component from react-bootstrap.
- Doesn't need to have any navigation yet.
- Add Helsinki logo and text "Huonevarausjärjestelmä". 
- Make the logo and text a link to the index page.
